---
permalink: san-host/task_preparing_to_transition_solaris_host_data_luns_with_zfs_file_system.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, solaris, host, data, lun, zfs 
summary: 在您將Solaris主機LUN（使用ZFS檔案系統Data ONTAP ）從以7-Mode運作的VMware轉型為叢集Data ONTAP 式VMware、之前、您必須先收集轉換程序所需的資訊。 
---
= 準備使用ZFS檔案系統來轉換Solaris主機資料LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在您將Solaris主機LUN（使用ZFS檔案系統Data ONTAP ）從以7-Mode運作的VMware轉型為叢集Data ONTAP 式VMware、之前、您必須先收集轉換程序所需的資訊。

這適用於複製型轉換和無複製轉換。

.步驟
. 在7-Mode控制器上、識別要轉換的LUN名稱：
+
’* LUN show*’

+
[listing]
----
 fas8040-shu01> lun show
        /vol/ufs/ufs1                  5g (5368709120)    (r/w, online, mapped)
        /vol/ufs/ufs2                  5g (5368709120)    (r/w, online, mapped)
        /vol/zfs/zfs1                  6g (6442450944)    (r/w, online, mapped)
        /vol/zfs/zfs2                  6g (6442450944)    (r/w, online, mapped)
----
. 在主機上、找出LUN的SCSI裝置檔案名稱：
+
「* sanlun LUN show*」

+
SCSI設備文件名位於"device Filene"（設備文件名）列中。

+
[listing]
----
# sanlun lun show
controller(7mode)/                    device                                            host                  lun
vserver(Cmode)       lun-pathname     filename                                          adapter    protocol   size    mode
--------------------------------------------------------------------------------------------------------------------------
fas8040-shu01        /vol/zfs/zfs2    /dev/rdsk/c0t60A98000383035356C2447384D396550d0s2 scsi_vhci0 FCP        6g      7
fas8040-shu01        /vol/zfs/zfs1    /dev/rdsk/c0t60A98000383035356C2447384D39654Ed0s2 scsi_vhci0 FCP        6g      7
fas8040-shu01        /vol/ufs/ufs2    /dev/rdsk/c0t60A98000383035356C2447384D39654Ad0s2 scsi_vhci0 FCP        5g      7
fas8040-shu01        /vol/ufs/ufs1    /dev/rdsk/c0t60A98000383035356C2447384D396548d0s2 scsi_vhci0 FCP        5g      7
----
. 列出zPool：
+
‘* zpool list*’

. 記錄zPool並取得與zPool相關的磁碟：
+
‘* zpool狀態_Pool-name_*

+
[listing]
----
# zpool list
NAME     SIZE  ALLOC   FREE  CAP  HEALTH  ALTROOT
n_pool  11.9G  2.67G  9.27G  22%  ONLINE  -

# zpool status
  pool: n_pool
 state: ONLINE
 scan: none requested
config:

        NAME                                     STATE     READ WRITE CKSUM
        n_pool                                   ONLINE       0     0     0
          c0t60A98000383035356C2447384D396550d0  ONLINE       0     0     0
          c0t60A98000383035356C2447384D39654Ed0  ONLINE       0     0     0

errors: No known data errors
----
. 列出並記錄ZFS儲存資源池中的ZFS資料集：
+
《* zflist*》

+
[listing]
----
# zfs list
NAME           USED  AVAIL  REFER  MOUNTPOINT
n_pool        2.67G  9.08G   160K  /n_pool
n_pool/pool1  1.50G  2.50G  1.50G  /n_pool/pool1
n_pool/pool2  1.16G  2.84G  1.16G  /n_pool/pool2
----

