---
permalink: san-host/task_bringing_windows_hosts_online_after_transition.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, windows, host, online 
summary: 使用適用於Windows主機的7-Mode Transition Tool（7MTT）來轉換LUN之後、您必須完成數個步驟、才能讓主機上線並重新開始服務資料。 
---
= 轉換後讓Windows主機上線
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用適用於Windows主機的7-Mode Transition Tool（7MTT）轉換LUN後、您必須完成數個步驟、才能讓主機上線並重新開始服務資料。

如果您正在執行無複製轉換（CFT）、則必須完成「vol rehost」的程序。請參閱 link:https://docs.netapp.com/us-en/ontap-7mode-transition/copy-free/index.html["7-Mode Transition Tool無複製移轉指南"] 以取得詳細資料。

* 對於複製型轉換（CBT）、請在完成7-Mode Transition Tool（7MTT）中的Storage Cutover（儲存設備轉換）作業之後、執行這些步驟。
* 對於CFT、請在完成7MTT中的匯入與資料組態作業之後、執行這些步驟。
+
.. 產生7-Mode to ONTAP VMware LUN對應檔案：
+
*** 對於複製型轉換、請從安裝7MTT的主機執行下列命令：+`* Transition CBT匯出lunmap -p _project name_-o _file_path_*
+
例如：

+
「* Transition CBT匯出lunmap -p SanWorkLoad -o c：/Lithraes/7-to-C-lun-mapping．csv*」

*** 對於無複製轉換、請從安裝7MTT的系統執行下列命令：+`* Transition CFT匯出lunmap -p _project name_-s _svm-name_-o _output-file_*
+

NOTE: 您必須為每個儲存虛擬機器（SVM）執行此命令。

+
例如：

+
'轉換CFT匯出lunmap -p SANWorkLoad -s svml-o cs/磁帶 庫/Documents/7-to-C-lun-mapping -svml.csv*'



.. 如果Windows主機是SAN開機且開機LUN已轉換、請開啟主機電源。
.. 更新FC BIOS、讓系統從叢集Data ONTAP 式的BIOS控制器上的LUN開機。
+
如需詳細資訊、請參閱HBA文件。

.. 在Windows主機上、從磁碟管理程式重新掃描磁碟。
.. 取得LUN序號、LUN ID、以及對應至主機之LUN的對應Windows實體磁碟編號。
+
*** 對於執行Data ONTAP SONTONTAPDSM的系統：請使用Data ONTAPDSM Management Extension嵌入式管理單元或Get-SanDisk Windows PowerShell Cmdlet。
*** 對於執行MSDSM的系統：使用庫存收集工具（ICT）。
+
LUN ID、LUN序號及對應的序號會擷取在SAN主機LUN索引標籤下。



.. 請使用LUN的LUN序號、LUN ID及LUN的對應Windows實體磁碟編號、以及LUN對應輸出、以及在預先轉換狀態中收集的資料、來判斷LUN是否已成功轉換。
.. 請注意已轉換LUN的實體磁碟編號是否已變更。
.. 使磁碟上線。
+
*** 使用Windows磁碟管理程式、將不屬於叢集容錯移轉的線上磁碟移轉。
*** 使用容錯移轉叢集管理程式、將屬於叢集容錯移轉一部分的線上磁碟帶入。


.. 如果您要轉換的主機正在執行Windows Server 2003、且您已移轉仲裁裝置、請在所有叢集節點上啟動叢集服務。
.. 如果在主機上啟用Hyper-V、並將傳遞裝置設定為VM、請從Hyper-V Manager修改設定。
+
由於轉換、相對應於傳遞裝置的LUN實體磁碟編號可能會有所變更。





*相關資訊*

xref:concept_what_the_inventory_collect_tool_is.adoc[庫存收集工具的功能]
