---
permalink: copy-based/concept_requirements_for_copy_based_transition.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, requirements 
summary: 您必須瞭解ONTAP 以複本為基礎的轉換作業的版本需求、授權要求及7-Mode轉換工具要求。 
---
= 複本型轉換的需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須瞭解ONTAP 以複本為基礎的轉換作業的版本需求、授權要求及7-Mode轉換工具要求。

* *《*》7-Mode來源系統* Data ONTAP
+
如需7-Mode Transition Tool支援移轉的7-Mode版本清單、請參閱 https://mysupport.netapp.com/matrix["NetApp 互通性對照表工具"]。

* *目標系統* ONTAP
+
這些ONTAP 版本支援複製型轉換。

+
|===
| 如果您的轉換目標正在執行... | 您必須使用此7-Mode Transition Tool版本... 


 a| 
支援的更新版本包括ONTAP ONTAP
 a| 
3.5.0



 a| 
支援的更新版本ONTAP
 a| 
3.4.0



 a| 
支援的更新版本ONTAP
 a| 
3.3.3



 a| 
更新版本9.7 P ONTAP


NOTE: 不支援較早9.7版本。
 a| 
3.3.2



 a| 
發行版9.6 P7或更新版本9.6 P ONTAP


NOTE: 不支援9.6版之前的版本。
 a| 
3.3.2



 a| 
發行版不含任何更新版本ONTAP ONTAP
 a| 
3.3.2或3.3.1



 a| 
叢集Data ONTAP 式發行版本8.1.4P4或更新版本8.x
 a| 
3.3.2或3.3.1

|===
* *授權要求*
+
SnapMirror必須在7-Mode儲存系統上獲得授權。如果7-Mode系統沒有SnapMirror授權、您可以從銷售代表處取得暫時的SnapMirror授權以進行移轉。

+
如果必須執行監管鏈驗證、則必須在目的地叢集上授權。SnapLock

* * 7-Mode Transition Tool服務*
+
若要讓資料複本排程生效、7-Mode Transition Tool服務必須永遠在安裝該工具的Windows或Linux系統上啟動並執行。不過、這並不需要網路介面處於作用中或開啟狀態、排程才會生效。您可以關閉Web介面、並在需要時重新登入。

* *移轉評估的儲存設備、主機和FC交換器版本需求*
+
如需7-Mode Transition Tool所支援評估的7-Mode版本、主機和FC交換器清單、請參閱 https://mysupport.netapp.com/matrix["NetApp 互通性對照表工具"]。


