---
permalink: copy-based/concept_considerations_for_deduplication_and_compression.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, deduplication, compression 
summary: 使用壓縮時、來源和目的地磁碟區必須屬於64位元Aggregate。在轉換期間、來源磁碟區上的所有壓縮與重複資料刪除節約效益都會透過網路保留。轉換後、目的地Volume會繼承來源Volume的所有壓縮和重複資料刪除屬性、以及儲存節約效益。 
---
= 重複資料刪除與壓縮的考量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用壓縮時、來源和目的地磁碟區必須屬於64位元Aggregate。在轉換期間、來源磁碟區上的所有壓縮與重複資料刪除節約效益都會透過網路保留。轉換後、目的地Volume會繼承來源Volume的所有壓縮和重複資料刪除屬性、以及儲存節約效益。

由於下列原因、轉換刪除重複資料和壓縮資料有助於降低轉換期間的網路頻寬：

* 共享區塊只會傳輸一次。
* 在傳輸過程中會維持壓縮。
* 壓縮與刪除重複資料會因為壓縮與重複資料刪除空間節省而導致傳輸規模變小、因此傳輸作業更快完成。


在轉換期間、您不應開始壓縮或重複資料刪除來源磁碟區上的現有資料。如果正在進行重複資料刪除或壓縮、您應該只在完成重複資料刪除或壓縮作業之後才開始轉換。因此、未進行重複資料刪除或未壓縮的資料和其他暫用中繼資料檔案不會透過網路傳送到目的地Volume。

為了讓重複資料刪除和壓縮在ONTAP 任何寫入到這個磁碟區的新資料上生效、您必須在轉換後啟用重複資料刪除和壓縮排程。

重複資料刪除技術從Data ONTAP 功能性的8.1開始、會在磁碟區中維護部分訂購的指紋資料庫、以及集合複本。如此一來、目的地系統就能從來源磁碟區節省空間、以及訂購指紋資料庫的複本。移轉之後、首次在新磁碟區上執行磁碟區效率時、會自動從目的地磁碟區中的複本建置Aggregate指紋資料庫。這可能會導致完成Volume效率作業所需的時間一次性增加。

如果您的來源Volume執行Data ONTAP 的是以8.1之前的7-Mode運作的功能、則必須使用「-scan -old-data option」參數執行「Volume Effize start」命令、以最佳化空間節約效益。移轉完成後、您應該確認重複資料刪除排程是否符合叢集的需求、並考慮改用Volume Eff效率 原則。
