---
permalink: copy-based/concept_prerequisites_for_transitioning_cifs_configurations.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, prerequisites, cifs, configurations 
summary: 只有在7-Mode系統和叢集符合特定先決條件時、7-Mode Transition Tool才會轉換CIFS組態。如果不符合任何條件、則此工具不會轉換組態。 
---
= 轉換CIFS組態的先決條件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
只有在7-Mode系統和叢集符合特定先決條件時、7-Mode Transition Tool才會轉換CIFS組態。如果不符合任何條件、則此工具不會轉換組態。



== 7-Mode必備條件

* 必須新增CIFS授權。
* 如果MultiStore 啟用了「不支援」授權、則必須將CIFS新增至擁有轉換磁碟區之vFiler單元允許的傳輸協定清單。
* CIFS必須在轉換期間設定及執行。
* CIFS的驗證類型必須是Active Directory（AD）或工作群組。




== 叢集先決條件

* 必須新增CIFS授權。
* CIFS必須新增至SVM允許的傳輸協定清單。
* 必須為SVM設定DNS。
* 下列CIFS驗證方法在ONTAP 不同的版本中均受支援：
+
** 叢集Data ONTAP 式的0.2.x和8.3.x支援AD驗證。
** 支援AD驗證和工作群組驗證的支援版本為9.0或更新版本。ONTAP


* 請使用下表來決定目標SVM上必須使用的驗證：
+
|===
| 7-Mode驗證方法 | 叢集Data ONTAP 式的0.2.x和8.3.x驗證方法 | 適用於更新版本的驗證方法ONTAP 


 a| 
廣告
 a| 
廣告
 a| 
廣告



 a| 
工作群組
 a| 
廣告
 a| 
工作群組或AD

|===
* 如果7-Mode CIFS伺服器與目標SVM CIFS伺服器之間的AD網域不相符、您可以將CIFS組態從7-Mode移轉至ONTAP Sf24。當偵測到AD網域名稱不相符時、此工具會觸發可接受的封鎖錯誤。若要繼續進行轉換、請確認封鎖錯誤。
* CIFS伺服器必須在套用組態階段（預先轉換）之前手動設定。
+
您可以使用下列兩種方式在SVM上建立CIFS伺服器：

+
|===
| 如果您想要... | 請執行下列動作... 


 a| 
將CIFS伺服器身分識別傳輸或保留至目標SVM
 a| 
** 您必須計畫在單一專案中、轉換來源7-Mode系統或VFiler裝置中的所有磁碟區。
+
這是必要的計畫、因為7-Mode系統在轉換後失去原始CIFS伺服器身分、無法服務用戶端。在一個專案中可移轉的最大Volume數為160；因此、為了保留CIFS伺服器身分識別、7-Mode系統最多可有160個磁碟區、而且所有這些磁碟區都必須在單一專案中移轉。

+
您可以使用下列兩個選項來建立CIFS伺服器：

+
... 適用於ONTAP 所有版本的不適用：
+
**** 在「套用組態」階段（預先轉換）之前、您必須使用暫時性的CIFS身分識別、在7-Mode系統上重新設定CIFS伺服器。
+
這項重新設定可讓您在SVM上設定原始CIFS伺服器身分識別。您必須驗證CIFS伺服器是否在7-Mode系統上以新的暫用身分執行「套用組態」階段（預先轉換）作業。在預先轉換期間、從7-Mode讀取CIFS組態需要執行此動作。

**** 您必須在目標SVM上設定具有原始7-Mode CIFS身分識別的CIFS伺服器。
**** 滿足這些條件之後、您就可以執行預先轉換作業。
+
然後您必須計畫在執行前置版本之後立即執行儲存轉換、以便用戶端存取ONTAP 各項資料。



... 適用於9.0至9.5版的更新版本：ONTAP
+
**** 使用「vserver CIFS modify」命令來變更CIFS伺服器名稱（CIFS伺服器NetBios名稱）。
+
使用此功能時、您應該在目標SVM上建立具有暫用身分識別的CIFS伺服器、然後執行套用組態（預先轉換）作業。

**** 在「套用組態」階段之後、您可以在目標叢集上執行「vserver CIFS modify」命令、以7-Mode CIFS身分識別取代目標SVM CIFS身分識別。








 a| 
使用新身分識別
 a| 
** 在「套用組態」階段（預先轉換）之前、您必須在目標SVM上使用新的CIFS身分識別來設定CIFS伺服器。
** 您必須在「apply configuration」（套用組態）階段（預先轉換）作業期間、確認CIFS伺服器已在7-Mode系統上啟動並執行。
+
在「Apply configuration」（套用組態）階段（預先轉換）期間、必須執行此動作才能從7-Mode系統讀取CIFS組態。

+
滿足這些條件之後、您就可以執行預先轉換作業。然後您可以測試SVM組態、並規劃執行儲存轉換作業。



|===


*相關資訊*

xref:concept_considerations_for_local_users_and_groups_transition.adoc[移轉CIFS本機使用者和群組的考量]
