---
permalink: copy-based/concept_transition_terminology.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, terminology 
summary: 瞭解7-Mode Transition Tool的相關轉換詞彙、有助於瞭解轉換程序。 
---
= 移轉術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
瞭解7-Mode Transition Tool的相關轉換詞彙、有助於瞭解轉換程序。

* *收集與評估*
+
在將資料和組態轉換為ONTAP 資料中心之前、您必須收集儲存環境的相關資訊、包括儲存系統、主機和應用程式。然後您必須評估這些系統的功能和特性、並找出這些功能在ONTAP 選定的版本中如何在轉換中運作。

* *移轉*
+
指將資料和組態從7-Mode磁碟區移轉至ONTAP VMware。在評估7-Mode控制器之後、應執行移轉。

* *專案*
+
在7-Mode Transition Tool中、專案可讓您設定及管理一組磁碟區的移轉作業。

+
轉換專案有三種類型：獨立式、一線和二線。

+
** *獨立專案*
+
此專案中的Volume與其他儲存系統中的Volume並無任何SnapMirror關係、或者您想要在不保留其SnapMirror關係的情況下、移轉這些Volume。

** *主要專案*
+
此專案中的Volume是SnapMirror關係的來源磁碟區。

** *二線專案*
+
此專案中的Volume是SnapMirror關係的目的地Volume。



* *專案群組*
+
在7-Mode Transition Tool中、專案群組是一個邏輯容器、可用來存放相關的移轉專案。系統中永遠有一個預設群組具有預設的群組名稱。

* *移轉對等關係*
+
轉換對等關係是一種授權機制、可讓SnapMirror在7-Mode儲存系統與叢集中的SVM之間建立關係、以便將資料從7-Mode磁碟區複製到ONTAP 以供轉換的SVM磁碟區。轉換對等關係只能由叢集管理員建立、並從叢集啟動。

* *移轉資料保護關係*
+
轉換資料保護（TDP）關係是在7-Mode系統與ONTAP VMware系統之間建立的Volume SnapMirror關係。

+
只有在轉換時才支援移轉資料保護。您不應該長期維持這種關係、因為ONTAP 無法將資料從一個故障磁碟區重新同步回一個7-Mode磁碟區。


