---
permalink: copy-based/task_starting_data_copy_for_a_transition_session.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, start, data, copy, project 
summary: 您可以從7-Mode Volume開始資料複本、並將其複製到ONTAP VMware Volume、以便進行基礎傳輸。當專案中設定的資料複本排程變成作用中時、即會開始進行基準傳輸。完成基礎傳輸之後、ONTAP 將根據資料複製排程定期更新此功能。 
---
= 開始執行移轉專案的資料複本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以從7-Mode Volume開始資料複本、並將其複製到ONTAP VMware Volume、以便進行基礎傳輸。當專案中設定的資料複本排程變成作用中時、即會開始進行基準傳輸。完成基礎傳輸之後、ONTAP 將根據資料複製排程定期更新此功能。

* 您必須執行專案的預先檢查、並解決所有錯誤。
* 您必須在來源與目的地系統之間設定專屬的高頻寬、低延遲網路、才能進行資料傳輸。
+

NOTE: 您可以使用SnapMirror多重路徑來平衡兩個路徑之間的資料傳輸負載。

* 必須為工作階段設定資料複本排程。


如果您要轉換至現有的SVM、則會在此作業期間建立磁碟區。如果您要轉換至新的SVM、則在此作業期間會建立SVM及其磁碟區。

SnapMirror關係是在7-Mode和ONTAP Mirrorvolume之間建立的。

.步驟
. 開始資料複本：
+
‘*轉換開始-p _project名稱_*’

+
如果啟動作業失敗且未啟動資料複本、您必須解決此問題、然後再次執行「Transition start」命令。

+
[listing]
----
7-Mode Transition Tool>transition start -p project_finance

[1/17 ] Project status checks                                      [      Ok       ]
[2/17 ] Validating 7-Mode system information                       [      Ok       ]
[3/17 ] Validating 7-Mode volumes information                      [      Ok       ]
[4/17 ] Validating Cluster-Mode system information                 [      Ok       ]
[5/17 ] Validating Cluster-Mode volume information                 [      Ok       ]
[6/17 ] Validating LIF information                                 [ Notifications ]
[7/17 ] WAFL prechecks                                             [      Ok       ]
[8/17 ] UNIX users and groups prechecks                            [   Warnings    ]
[9/17 ] SnapMirror prechecks                                       [ Notifications ]
[10/17] NFS prechecks                                              [   Warnings    ]
[11/17] Networking prechecks                                       [ Notifications ]
[12/17] CIFS prechecks                                             [   Warnings    ]
[13/17] Name services prechecks                                    [   Warnings    ]
[14/17] SAN prechecks                                              [      Ok       ]
[15/17] Creating Cluster-Mode volumes                              [      Ok       ]
[16/17] Establishing SnapMirror relationships between the 7-Mode and Cluster-Mode volumes                                                            [      Ok       ]
[17/17] Initializing SnapMirror relationships between the 7-Mode and Cluster-Mode volumes                                                            [      Ok       ]

Operation summary:
------------------
The 'start' operation is completed with warnings and notifications.

 0  Errors - No action required
22  Warnings - Need your attention!
16  Notifications - Please review
102  Informational messages

Do you want to see a detailed report {yes, no} [yes]:

22 Warnings:
------------
20362: Checking whether 7-Mode UNIX groups' names are in use in the Vserver 'vs2'.  [    Warning    ]
  > The following 7-Mode UNIX groups' names are already in use in the Vserver 'vs2'.
  > AFFECTED-OBJECTS: { daemon }

20372: Checking whether 7-Mode UNIX groups' ids are in use in the Vserver 'vs2'.    [    Warning    ]
  > The following 7-Mode UNIX groups' ids are already in use in the Vserver 'vs2'.
  > AFFECTED-OBJECTS: { daemon }
----
+
專案會移至複本基準狀態。完成基準傳輸之後、專案會移至複本更新狀態。


