---
permalink: copy-based/task_creating_a_transition_project.html 
sidebar: sidebar 
keywords: create, transition, project, ontap, copy, based, transition 
summary: 建立移轉專案包括選取7-Mode磁碟區並將其對應至儲存虛擬機器（SVM\）、對應介面、以及建立SnapMirror關係的資料複本排程。 
---
= 建立轉換專案
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
建立移轉專案包括選取7-Mode磁碟區並將其對應至儲存虛擬機器（SVM）、對應介面、以及建立SnapMirror關係的資料複本排程。

您必須在叢集上建立所需的SVM。

專案中的所有磁碟區都會移轉至相同的SVM。如果您要將磁碟區移轉至不同的SVM、則必須建立多個專案。

如果目標叢集執行Data ONTAP 的是EAS8.3.1或更早版本、而您想要在NAS磁碟區的讀寫模式下執行預先轉換作業、則必須為NAS磁碟區和SAN磁碟區建立個別專案。如果專案中有SAN磁碟區、則不支援預先轉換讀取/寫入模式、因此需要執行此動作。

如果專案包含SnapLock 「循環法規遵循」磁碟區、而您想要在非SnapLock Compliance磁碟區的讀寫模式下執行預先轉換作業、則必須針對SnapLock 「循環法規遵循」磁碟區和「非SnapLock Compliance」磁碟區建立個別專案。如果SnapLock 您的專案中有「更新法規遵循」磁碟區、則需要執行此動作、因為不支援預先轉換讀寫模式。

.步驟
. 從首頁選取*複本型轉換*移轉方法、然後按一下*開始規劃*。
+
如果新專案所需的控制器和叢集尚未新增、您可以在「輸入裝置認證」窗格中輸入詳細資料。

. 確認Data ONTAP 所有在7-Mode系統和ONTAP 支援系統中運作的必要資訊均已新增至工具、然後按一下*「下一步*」。
+
此時會出現「選取來源Volume」頁面。

. 選取您要轉換的7-Mode磁碟區。
+
.. 從7-Mode Controller（7-Mode控制器）窗格中、選取您要新增磁碟區的7-Mode控制器或vFiler單元。
.. 新增您要納入專案群組的磁碟區：
+
|===
| 如果您想要轉換... | 然後... 


 a| 
獨立磁碟區
 a| 
針對您要轉換的磁碟區、選取*「轉換為獨立*」。

如果您從此欄選取第一個Volume、就會建立獨立專案。



 a| 
Volume SnapMirror關係
 a| 
... 針對所有主要磁碟區、選取*使用SnapMirror關係進行移轉*。
+
建立兩個專案：一是主要磁碟區的主要專案、另一是次要專案。

... *可選：*如果項目中不包括輔助控制器，請在需要額外的儲存系統認證對話框中輸入控制器的詳細信息。


|===
+
如果您的磁碟區中至少有一個LUN、則該磁碟區類型會顯示為SAN。

+
磁碟區名稱上提供的超連結會開啟一個對話方塊、列出磁碟區中的qtree和LUN及其屬性。

+

TIP: 最佳做法是讓單一專案中的所有磁碟區都具有相同的定義（獨立、主要或次要）。例如、專案應包含所有獨立磁碟區、而非獨立與SnapMirror關係的混合。

.. 選取專案中要包含的所有磁碟區之後、請按一下「*建立專案並繼續*」、從出現的對話方塊中輸入專案名稱和專案群組詳細資料、然後按一下「*儲存*」以建立專案。


. 選擇用於SnapMirror資料複本的7-Mode IP位址和多重路徑IP位址。
+
.. 輸入7-Mode資料複製IP位址。
+
依預設、此欄位會預先填入7-Mode系統的管理IP位址。如果需要、您可以使用資料複製權限、將此IP位址變更為任何有效的IPv4位址。

.. 如果您要使用多個路徑來平衡資料傳輸的負載、請在「IP組態」窗格中輸入IP位址、然後按一下「*下一步*」。


. 在Select SVM（選擇SVM）頁面中、選取目標叢集和SVM、然後依照下列步驟進行：
+
.. 按一下「Select a cluster Data ONTAP 」（選取叢集式）下拉式清單中的叢集名稱、選取目標叢集。
+
SVM會載入Select SVM窗格。

.. 從Select SVM（選擇SVM）窗格中選取要轉換磁碟區的目標SVM。
.. 單擊 * 下一步 * 。


+
若要將7-Mode Volume轉換為MetroCluster VMware組態ONTAP 、SVM子類型必須是「同步來源」。

+
+如果您選取屬於叢集Data ONTAP 式VMware 8.2的SVM、會顯示一個對話方塊、確認本機使用者和群組、或是在7-Mode儲存系統上設定CIFS共用或檔案。7-Mode Transition Tool不支援將本機使用者和群組移轉至叢集Data ONTAP 式的VMware 8.2。如果您有本機使用者和群組、您可以選擇屬於ONTAP 支援版本的SVM。

. 在SVM稽核記錄目的地路徑對話方塊中、輸入目的地SVM的路徑、以便從7-Mode儲存系統轉換稽核組態。
+
此路徑可用來將稽核記錄儲存在ONTAP 功能完善的系統中。

. 在「對應磁碟區」頁面中、選取要轉換的目標磁碟區、將每個來源磁碟區對應至所需的Aggregate。
+
.. 從「在目標叢集上對應原始磁碟區以集合體」窗格中、選取必須複製7-Mode磁碟區的集合體。
.. 若要變更叢集上目標磁碟區的名稱、請在*目標磁碟區*欄位中輸入不同的名稱。
.. 單擊 * 下一步 * 。


+
如果專案中包含的所有磁碟區和qtree均設定為僅處理NFS要求、則您不需要提供稽核路徑、因為稽核組態並未轉換（即使您提供稽核路徑、此輸入也會被忽略）。

. 從「網路組態」窗格中、提供必須在SVM上建立的LIF相關資訊。
+

NOTE: FC與iSCSI生命里數無法轉換。您必須在SVM上手動建立。

+
|===
| 如果您想要... | 然後... 


 a| 
轉換現有的7-Mode IP位址
 a| 
.. 按一下*選取7-Mode LIF*。
.. 選取所需的7-Mode IP位址、並提供目標節點和目標連接埠詳細資料。
.. 按一下「 * 儲存 * 」。




 a| 
建立新的LIF
 a| 
.. 按一下「*新增LIF*」。
.. 在出現的對話方塊中、輸入新LIF的詳細資料。
.. 按一下「 * 儲存 * 」。


|===
+
若要在成功轉換後提供網路連線、您必須將7-Mode IP位址轉換成ONTAP 類似的靜態網路拓撲。例如、如果在實體連接埠上設定7-Mode IP位址、則IP位址應轉換至ONTAP 位於VMware的適當實體連接埠。同樣地、在VLAN連接埠或介面群組上設定的IP位址也應該轉換到ONTAP 適當的VLAN連接埠或是在支援中的介面群組。

. 新增所有必要的IP位址之後、按一下*下一步*。
. 在「設定排程」頁面中、設定基準和遞增傳輸的資料複本排程、並行Volume SnapMirror傳輸數、以及SnapMirror傳輸的節流限制。
+
您可以提供資料複製排程和節流限制、以有效管理DR和轉換資料複製作業。您可以為每個專案建立最多七個排程的多個排程。例如、您可以建立自訂的工作日和週末排程。

+

NOTE: 排程會根據來源7-Mode控制器時區而生效。

+
.. 在「設定排程」窗格中、按一下「*建立排程*」。
.. 在「建立資料複製排程」對話方塊中、輸入新排程的名稱。
.. 在「週期性天數」窗格中、選取*每日*或*選取天數*、以指定資料複製作業應執行的天數。
.. 在「時間間隔」窗格中、指定資料傳輸的*開始時間*和*持續時間*。
.. 在「時間間隔」窗格中、指定*更新頻率*進行遞增傳輸、或選取*持續更新*。
+
如果您啟用持續更新、則更新的最小延遲時間為5分鐘、視並行SnapMirror傳輸的可用度而定。

.. 在「轉換資料複製作業參數（根據Volume SnapMirror）」窗格中、指定並行Volume SnapMirror傳輸的最大數量（以執行時間和數字的可用SnapMirror傳輸百分比表示）、以及節流限制（專案中所有磁碟區的最大頻寬）。
+

NOTE: 欄位中提供的預設值為建議值。變更預設值時、您必須分析7-Mode SnapMirror排程、並確保所提供的值不會影響這些排程。

.. 按一下「 * 建立 * 」。
+
新排程會新增至「Transition Schedule」（轉換排程）窗格。

.. 新增所有必要的資料複製排程之後、請按一下*下一步*。


. 如果SnapLock 您有要轉換的數據區、請在轉換後規劃需要驗證保管鏈的磁碟區。
+
.. 選擇需要SnapLock 驗證保管鏈的來源供應鏈。
+
監管鏈驗證程序僅支援讀取/寫入7-Mode SnapLock 的驗證功能、不支援唯讀磁碟區。只有檔案名稱含有Ascii字元的功能區才支援監管鏈驗證。SnapLock

.. 提供ONTAP 有關將用於儲存保管鏈驗證作業期間所產生指紋資料的資料的資料。
+
此SVM上必須已存在此SVM磁碟區。ONTAP

.. 單擊 * 下一步 * 。




*相關資訊*

xref:concept_guidelines_for_creating_a_data_copy_schedule.adoc[建立資料複本排程的考量事項]

xref:task_creating_schedule_for_snapmirror_transfers.adoc[建立SnapMirror傳輸的資料複製排程]

xref:concept_managing_snapmirror_transfers_and_schedule.adoc[管理SnapMirror傳輸與排程]

xref:task_transitioning_volumes_by_excluding_a_subset_of_configurations.adoc[使用CLI自訂7-Mode組態的轉換]

xref:task_managing_logical_interfaces.adoc[管理邏輯介面]

xref:task_removing_volumes_from_a_project.adoc[從專案移除磁碟區]
