---
settings:
  name: ONTAP 7-Mode Transition
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-tw,us-en,ja-jp,zh-cn,ko-kr,fr-fr,de-de
sidebar:
  entries:
  - title: 7-Mode轉換
    url: "/index.html"
  - title: 版本資訊
    url: "/releasenotes.html"
  - section: command-map
  - section: install-admin
  - section: copy-based
  - section: copy-free
  - section: inventory-collect
  - section: snapmirror
  - section: san-host
  - title: 法律聲明
    url: "/reference_legal_notices.html"
homepage:
  tiles:
  - title: 開始使用
    links:
    - title: 新增功能
      summary: 瞭解最新版7-Mode Transition Tool的新功能
      url: releasenotes.html
    - title: 安裝7-Mode Transition Tool
      summary: 瞭解如何在Microsoft Windows或Linux上安裝此工具
      url: "/install-admin/concept_transition_to_clustered_ontap_using_7mtt.html"
    - title: 收集轉換所需的資料
      summary: 瞭解如何收集轉換過程中不可或缺的資訊
      url: "/inventory-collect/concept_collecting_host_and_storage_inventory_information_for_transition_assessment.html"
  - title: 適用於7-mode系統管理員的命令對應
    links:
    - title: 7-Mode命令如何對應ONTAP 至VMware指令
      summary: 尋找ONTAP 7-Mode命令的等效功能
      url: "/command-map/reference_how_7_mode_commands_map_to_clustered_ontap_commands.html"
    - title: 7-Mode選項如何對應ONTAP 至VMware指令
      summary: 瞭解7-Mode選項如何對應ONTAP 至指令參數
      url: "/command-map/reference_how_7_mode_options_map_to_clustered_ontap_commands.html"
    - title: 7-Mode組態檔如何對應ONTAP 至各種指令
      summary: 瞭解7-Mode組態檔如何對應ONTAP 至各種組態命令
      url: "/command-map/reference_how_7_mode_configuration_files_map_to_clustered_ontap_commands.html"
  - title: 轉換方法
    links:
    - title: 複本型轉換
      summary: 使用工具執行從7-Mode到ONTAP VMware的複本轉換
      url: "/copy-based/concept_copy_based_transition_workflow.html"
    - title: 無複製轉換
      summary: 使用工具執行從7-Mode到ONTAP VMware的無複本轉換
      url: "/copy-free/task_copy_free_transition_workflow.html"
    - title: 使用SnapMirror移轉資料
      summary: 瞭解如何ONTAP 使用SnapMirror命令、將資料從7-Mode移轉至VMware
      url: "/snapmirror/task_transitioning_7_mode_volumes_using_snapmirror.html"
  - title: SAN主機移轉與補救
    links:
    - title: VMware ESXi
      summary: 瞭解VMware ESXi主機的移轉前後需求
      url: "/san-host/concept_vmware_esxi_host_remediation.html"
    - title: Red Hat Enterprise Linux
      summary: 瞭解Red Hat Enterprise Linux主機的轉換前與轉換後需求
      url: "/san-host/concept_linux_host_remediation.html"
    - title: Windows
      summary: 瞭解Microsoft Windows主機的轉換前與轉換後步驟
      url: "/san-host/concept_windows_host_remediation.html"
product-family:
  name: ONTAP
  repo: ontap-family
  sidebar_label: 所有ONTAP 產品文件
