---
permalink: copy-free/concept_supported_and_unsupported_data_protection_relationships.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, data, protection, supported, unsupported, configurations 
summary: 您可以移轉屬於SnapMirror關係一部分的磁碟區。不過、部分資料保護和災難恢復組態不支援移轉、因此您必須手動執行一些步驟來轉換這些組態。 
---
= 資料保護移轉：支援及不支援的組態
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以移轉屬於SnapMirror關係一部分的磁碟區。不過、部分資料保護和災難恢復組態不支援移轉、因此您必須手動執行一些步驟來轉換這些組態。



== 支援的組態

您可以使用7-Mode Transition Tool來轉換Volume SnapMirror關係。您可以執行一線和二線HA配對的無複本轉換。然後、您必須在轉換後手動設定Volume SnapMirror關係。

xref:task_transitioning_a_snapmirror_relationship.adoc[轉換SnapMirror關係]



== 不支援的組態

* 相依關係SnapVault
+
可以移轉來源為「支援」關係的磁碟區SnapVault 、但SnapVault 不轉換「支援」關係。只SnapVault 有SnapVault 在停止執行還原備份之後、才能移轉做為「還原」關係目的地的Volume。

+
http://["NetApp技術報告4052：成功移轉至叢集Data ONTAP 式的更新版本（Data ONTAP NetApp技術報告4052）"]

* qtree SnapMirror關係
+
具有qtree SnapMirror關係來源的qtree磁碟區可以轉換、但qtree SnapMirror關係不會轉換。只有在qtree SnapMirror關係中斷之後、才能移轉具有qtree SnapMirror關係目的地qtree的磁碟區。

* 災難恢復vFiler單元
+
災難恢復vFiler單元的來源磁碟區可以移轉、但災難恢復vFiler單元並未轉換。作為災難恢復vFiler單元目的地的磁碟區、只有在刪除災難恢復關係之後、才能移轉。

* NDMP組態
+
完成轉換後、您必須手動設定ONTAP 更新後的備份原則、以利在支援更新的資料區。

+
https://["使用磁帶備份來保護資料"]

* 同步SnapMirror關係
+
此功能不受ONTAP 支援於此；不過、屬於此關係一部分的磁碟區可以轉換。



*相關資訊*

xref:task_customizing_configurations_for_transition.adoc[自訂7-Mode組態的轉換]
