---
permalink: copy-free/task_exporting_7_mode_system_and_hardware_information.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, exporte, storage, configurations, halt 
summary: 轉換的轉換時間範圍從匯出階段開始。在此階段、工具會從7-Mode系統收集系統資訊、磁碟櫃詳細資料及儲存組態、然後停止7-Mode儲存系統。 
---
= 匯出儲存組態並停止7-Mode系統
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
轉換的轉換時間範圍從匯出階段開始。在此階段、工具會從7-Mode系統收集系統資訊、磁碟櫃詳細資料及儲存組態、然後停止7-Mode儲存系統。

* 在7-Mode系統上、服務處理器（SP）或遠端LAN模組（RLM）必須設定有一個IPV4位址。
* 所有用戶端都必須從7-Mode系統中斷連線（藉由卸載NFS匯出、中斷CIFS共用及關閉SAN主機）、但適用的NAS和SAN服務必須在7-Mode系統上執行。
+

IMPORTANT: 您不得停止任何傳輸協定服務、因為它們是從7-Mode儲存系統收集傳輸協定組態所需的。

* 在此作業期間寫入7-Mode磁碟區的任何資料都會遺失。
* 在此作業期間、您不得在7-Mode系統上執行任何管理作業。
* 此工具會在匯出階段執行下列作業：
+
** 收集所有Volume與儲存組態
** 為每個轉換Aggregate建立Snapshot複本
+
如果您決定在轉換的任何階段回復至7-Mode、工具會使用這些Snapshot複本進行還原作業。

** 以維護模式開機7-Mode控制器
** 從7-Mode控制器移除磁碟擁有者
** 停用目標叢集節點上的磁碟自動指派




.步驟
. 按一下*匯出並停止*。
+
畫面會顯示一則訊息、列出此作業的重要考量。

. 按一下「*確認用戶端存取已中斷連線*」核取方塊。
. 按一下「*是*」以繼續匯出及停止作業。
+
隨即顯示操作結果。

. 請等待作業完成、然後執行下列步驟以儲存作業結果並收集工具記錄：
+
.. 按一下*「另存為CSV*」、將作業結果儲存在檔案中。
.. 按一下「*收集工具記錄*」以建立所有轉換記錄檔的備份。
+
最佳做法是在每次轉換作業之後儲存記錄檔。

.. 按一下「*關閉*」以關閉操作結果視窗。


+
如果作業需要很長時間才能完成、您可以按一下*在背景中執行*來結束作業結果視窗。當作業在背景執行時、您不應編輯專案或執行任何其他工作。然後、您可以從「操作歷程記錄」標籤檢視操作結果。


