---
permalink: copy-free/task_applying_svm_configurations.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, apply, svm, configurations 
summary: 您必須在SVM資源配置階段之前手動套用部分組態。然後、您可以使用工具、將在7-Mode控制器\（/etc/directory\中的檔案）或vFiler單元層級中定義的所有組態套用至對應的SVM。 
---
= 套用SVM組態
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須在SVM資源配置階段之前手動套用部分組態。然後、您可以使用工具、將在7-Mode控制器（位於「/etc/」目錄中的檔案）或vFiler單元層級中定義的所有組態、套用至對應的SVM。

如果您不想將所有組態移轉至目標SVM、則必須設定要排除在SVM上的組態內容。

xref:task_customizing_configurations_for_transition.adoc[自訂7-Mode組態的轉換]

* NFS匯出、CIFS共用和LUN對應等組態不會套用至SVM配置階段的SVM。
* 工具會在SVM資源配置階段的SVM上套用下列組態：
+
** *名稱服務*
+
*** DNS組態
*** LDAP組態
*** NIS組態
*** 名稱服務交換器組態
*** 主機組態
*** UNIX使用者與群組
*** 網路群組組組態


** *聯網*
+
*** 選取要轉換的現有7-Mode IP位址會以系統管理的當機狀態建立。
+
在匯入階段、這些IP位址會設定為管理啟動狀態。

*** 新的IP位址會在系統管理啟動狀態下建立。


** * NFS*
+
NFS選項

** * CIFS *
+
*** CIFS偏好的DC組態
*** 使用者對應組態
*** Widgelinks組態
*** CIFS選項
*** 稽核組態


** * SAN*
+
FC與iSCSI服務

+
[IMPORTANT]
====
您無法在成功完成此作業後重新執行。

因此、如果您在此作業之後對7-Mode控制器層級組態進行任何變更、則必須在匯出階段之前、手動將組態轉換至目標SVM。例如、如果您將新的VFiler裝置新增至7-Mode控制器、並在這項作業之後將其對應至SVM、則必須手動將該VFiler裝置的組態轉換至對應的SVM。另一個範例是、如果您在SVM資源配置階段之後、在7-Mode控制器上新增部分UNIX使用者、則必須在對應的SVM上手動建立這些UNIX使用者。

====




.步驟
. 按一下「*套用SVM組態*」、將7-Mode組態套用至目標SVM。
+
隨即顯示確認訊息、列出此作業的重要考量。

. 按一下「*是*」繼續。
. 操作完成後、請執行下列步驟：
+
.. 按一下*「另存為CSV*」、將作業結果儲存在檔案中。
.. 按一下*「收集專案記錄」*、建立所有轉換記錄檔的備份。
+
最佳做法是在每次轉換作業之後儲存記錄檔。

.. 按一下「*關閉*」以關閉操作結果視窗。


+
如果作業需要很長時間才能完成、您可以按一下*在背景中執行*來結束作業結果視窗。當作業在背景執行時、您不應編輯專案或執行任何其他工作。然後、您可以從「操作歷程記錄」標籤檢視操作結果。

. 手動驗證並測試套用至目標SVM的組態、然後進行必要的變更。
. 手動驗證外部名稱伺服器的連線能力。

