---
permalink: copy-free/task_transitioning_primary_and_secondary_systems_of_a_snapmirror_relationship_in_parallel.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, primary, secondary, system, snapmirror, relationship, parallel 
summary: 您可以並行轉換包含7-Mode SnapMirror關係磁碟區的主要和次要HA配對。然後、Data ONTAP 您必須在轉換後、在叢集式的SnapMirror中手動設定Volume SnapMirror關係。SnapMirror關係會在轉換後保留、而不需要重新建立基準。 
---
= 以SnapMirror關係並行轉換一線和二線系統
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以並行轉換包含7-Mode SnapMirror關係磁碟區的主要和次要HA配對。然後、Data ONTAP 您必須在轉換後、在叢集式的SnapMirror中手動設定Volume SnapMirror關係。SnapMirror關係會在轉換後保留、而不需要重新建立基準。

您必須準備好來源和目的地叢集、以便轉換SnapMirror關係。

xref:task_preparing_cluster_for_transitioning_volume_snapmirror_relationships.adoc[準備叢集以轉換Volume SnapMirror關係]

您必須在同一個轉換視窗中同時轉換次要HA配對和主要HA配對。

.步驟
. 在7-Mode Transition Tool中、執行兩個HA配對的無複本轉換、其中包含7-Mode Volume SnapMirror關係的主要和次要Volume。
+
在轉換包含次要磁碟區的7-Mode HA配對之前、7-Mode SnapMirror關係無需手動介入。這可確保7-Mode次要Volume可轉換為ONTAP 唯讀Volume至VMware。

+
xref:task_performing_copy_free_transition_of_7_mode_aggregates.adoc[使用無複本轉換來轉換7-Mode Aggregate]

. 在包含轉換的主要和次要磁碟區的SVM之間建立叢集間SVM對等關係。
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sag/home.html["系統管理"]

. 在轉換的主要和次要磁碟區之間建立Volume SnapMirror關係。
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-sm-ic-cg/home.html["Volume災難恢復快速準備"]

. 在目的地磁碟區上、重新同步SnapMirror關係的來源磁碟區和目的地磁碟區：
+
SnapMirror重新同步*

+

IMPORTANT: 來源與目的地磁碟區之間至少必須存在一個通用的Snapshot複本。

+
*疑難排解：*如果通用Snapshot複本是在Data ONTAP 8.1之前的版本中建立、SnapMirror重新同步將會失敗。您可以在進階權限層級中使用「-fs-version」參數搭配「volume snapshot show」命令、來檢視建立Snapshot複本的版本。如果遇到此問題、請中斷SnapMirror關係、然後執行重新同步。

. 監控SnapMirror資料傳輸的狀態：
+
SnapMirror SHOGAL*

+

IMPORTANT: 在成功完成重新同步之前、您不得在來源與目的地磁碟區上執行任何作業、例如Volume Move或SnapMirror中斷。請確保重新同步不會中斷並順利完成、否則磁碟區可能會進入不一致的狀態。

. 提交次要專案的移轉作業、接著是主要專案。
+
xref:task_committing_7_mode_aggregates_to_clustered_ontap_format.adoc[提交無複本移轉專案]



*相關資訊*

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["指令ONTAP"]

https://docs.netapp.com/us-en/ontap/["系統管理員"]
